type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
custom-flatpaks: # this section is optional
    - Brave Browser: com.brave.Browser
    - WebCord: io.github.spacingbat3.webcord
    - Spotify: com.spotify.Client
    - qBittorrent: org.qbittorrent.qBittorrent
    - Anki: net.ankiweb.Anki
    - Flatseal: com.github.tchx84.Flatseal
    - GIMP: org.gimp.GIMP
    - Obsidian: md.obsidian.Obsidian
    - Geary: org.gnome.Geary
    #- mpv: io.mpv.Mpv
    - Celluloid: io.github.celluloid_player.Celluloid
    - LibreOffice: org.libreoffice.LibreOffice
    - Bottles: com.usebottles.bottles
    # - Krita: org.kde.krita
