modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README
  - type: rpm-ostree
    repos:
      #- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - neovim
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - Brave Browser: com.brave.Browser
        - WebCord: io.github.spacingbat3.webcord
        - Spotify: com.spotify.Client
        - qBittorrent: org.qbittorrent.qBittorrent
        - Anki: net.ankiweb.Anki
        - Flatseal: com.github.tchx84.Flatseal
        - GIMP: org.gimp.GIMP
        - Obsidian: md.obsidian.Obsidian
        - Geary: org.gnome.Geary
          #- mpv: io.mpv.Mpv
        - Celluloid: io.github.celluloid_player.Celluloid
        - LibreOffice: org.libreoffice.LibreOffice
        - Bottles: com.usebottles.bottles
      remove:
    user:
      #repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      #repo-name: flathub

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
