type: rpm-ostree
repos:
# - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
install:
  - fcitx5
  - kcm-fcitx5
  - fcitx5-chinese-addons
  - fcitx5-hangul
remove:
# - balh
